### ISSUE TITLE
collective.relationfieldwidget Realease

### ISSUE THREAD

**Issue by Martronic-SA** [collective/collective.github.com#933]
Could someone make a release of collective.relationfieldwidget on pypi so it can be used by everybody?

Thank you!

**Comment by mauritsvanrees** [comment]
I suggest you ask in the issue tracker of that package.
Ah, you already did that a while ago with no answer... https://github.com/collective/collective.relationfieldwidget/issues/1
Then I suggest you ping the creator in that issue. Not everyone sees all issues or notifications.

I will leave this issue open for now, because I guess it would be fine if someone else creates a release using the 'collective' PyPI user.

**Comment by Martronic-SA** [comment]
Still no response...

**Comment by jensens** [comment]
@Martronic-SA if you have any questions about how to release or other processes you probably find a broader audience at https://community.plone.org - i close this one here
